# ~/shopmicro/frontend/Dockerfile
FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /usr/share/nginx/html/index.html
COPY orders-dashboard.html /usr/share/nginx/html/orders-dashboard.html
COPY users-dashboard.html /usr/share/nginx/html/users-dashboard.html
COPY products-dashboard.html /usr/share/nginx/html/products-dashboard.html
