# ~/shopmicro/k8s/api-gateway.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: shopmicro
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: jpou/shopmicro-api-gateway:latest
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
  - port: 80
    targetPort: 80
