# ~/shopmicro/k8s/secrets-db.yml

apiVersion: v1
kind: Secret
metadata:
  name: db-root-password-products
  namespace: shopmicro
type: Opaque
data:
  password: c3VwZXJzZWNyZXRwYXNzd29yZA==

---
apiVersion: v1
kind: Secret
metadata:
  name: db-root-password-orders
  namespace: shopmicro
type: Opaque
data:
  password: c3VwZXJzZWNyZXRwYXNzd29yZA==

---
apiVersion: v1
kind: Secret
metadata:
  name: db-root-password-users
  namespace: shopmicro
type: Opaque
data:
  password: c3VwZXJzZWNyZXRwYXNzd29yZA==

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-password
  namespace: shopmicro
type: Opaque
data:
  password: cmFiYml0c2VjcmV0NDU2

---
apiVersion: v1
kind: Secret
metadata:
  name: userservice-secret-key
  namespace: shopmicro
type: Opaque
data:
  secretkey: c2VjcmV0c3VwZXJzZWNyZXQxMjM=
